/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_freemonad_paridroid_PariNative */

#ifndef _Included_org_freemonad_paridroid_PariNative
#define _Included_org_freemonad_paridroid_PariNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_freemonad_paridroid_PariNative
 * Method:    paridroidInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_freemonad_paridroid_PariNative_paridroidInit
  (JNIEnv *, jclass);

/*
 * Class:     org_freemonad_paridroid_PariNative
 * Method:    paridroidEval
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freemonad_paridroid_PariNative_paridroidEval
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_freemonad_paridroid_PariNative
 * Method:    getHistSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freemonad_paridroid_PariNative_getHistSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
